version: '3.7'

services:
  openslide-winbuild:
    image: openslide-winbuild:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOME=/workspace
    volumes:
      - .:/workspace
